# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-83943-ranjithgowda-Surface-Laptop-3/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z007sclg400-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_0_0
    /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_1_0
    /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_2_0
  } {
      /home/ranjithgowda/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/ranjithgowda/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ipshared/52b4/src/Amp_Offset_Unit.sv
      /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ipshared/52b4/src/DAC_Calibration_Unit.sv
      /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ipshared/52b4/src/NCO_Phase_Accum.sv
      /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ipshared/52b4/src/SPI_Module.sv
      /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ipshared/52b4/src/Saw_Tri_Squ.sv
      /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ipshared/52b4/src/mux6to1.sv
      /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ipshared/52b4/hdl/wavegen_v1_0_AXI.v
      /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ipshared/52b4/hdl/wavegen_v1_0.v
    }
      rt::read_verilog -include {
    /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_0_0
    /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_1_0
    /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_2_0
  } {
      /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ipshared/52b4/bd/BRAM/synth/BRAM.v
      /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ipshared/52b4/bd/BRAM/hdl/BRAM_wrapper.v
      /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/synth/system_wavegen_0_2.v
    }
      rt::read_vhdl -lib xpm /home/ranjithgowda/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_5 /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ipshared/25a8/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_0_0/synth/BRAM_blk_mem_gen_0_0.vhd
      /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_1_0/synth/BRAM_blk_mem_gen_1_0.vhd
      /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_2_0/synth/BRAM_blk_mem_gen_2_0.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top system_wavegen_0_2
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-83943-ranjithgowda-Surface-Laptop-3/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
