# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.srcs/sources_1/bd/system/ip/system_wavegen_0_2/system_wavegen_0_2.xci
# IP: The module: 'system_wavegen_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_2_0/BRAM_blk_mem_gen_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BRAM_blk_mem_gen_2_0 || ORIG_REF_NAME==BRAM_blk_mem_gen_2_0} -quiet] -quiet

# IP: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_1_0/BRAM_blk_mem_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BRAM_blk_mem_gen_1_0 || ORIG_REF_NAME==BRAM_blk_mem_gen_1_0} -quiet] -quiet

# IP: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_0_0/BRAM_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BRAM_blk_mem_gen_0_0 || ORIG_REF_NAME==BRAM_blk_mem_gen_0_0} -quiet] -quiet

# XDC: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_2_0/BRAM_blk_mem_gen_2_0_ooc.xdc

# XDC: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_1_0/BRAM_blk_mem_gen_1_0_ooc.xdc

# XDC: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_0_0/BRAM_blk_mem_gen_0_0_ooc.xdc

# XDC: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/BRAM_ooc.xdc

# IP: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.srcs/sources_1/bd/system/ip/system_wavegen_0_2/system_wavegen_0_2.xci
# IP: The module: 'system_wavegen_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_2_0/BRAM_blk_mem_gen_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BRAM_blk_mem_gen_2_0 || ORIG_REF_NAME==BRAM_blk_mem_gen_2_0} -quiet] -quiet

# IP: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_1_0/BRAM_blk_mem_gen_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BRAM_blk_mem_gen_1_0 || ORIG_REF_NAME==BRAM_blk_mem_gen_1_0} -quiet] -quiet

# IP: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_0_0/BRAM_blk_mem_gen_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BRAM_blk_mem_gen_0_0 || ORIG_REF_NAME==BRAM_blk_mem_gen_0_0} -quiet] -quiet

# XDC: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_2_0/BRAM_blk_mem_gen_2_0_ooc.xdc

# XDC: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_1_0/BRAM_blk_mem_gen_1_0_ooc.xdc

# XDC: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/ip/BRAM_blk_mem_gen_0_0/BRAM_blk_mem_gen_0_0_ooc.xdc

# XDC: /home/ranjithgowda/Documents/FPGA/Projects/R_Project_SOC/R_Project_SOC/Project/gpio/gpio.gen/sources_1/bd/system/ip/system_wavegen_0_2/bd/BRAM/BRAM_ooc.xdc
